use Customer_Shopping_Behaviour
SELECT name FROM sys.tables;
SELECT * FROM customer;

SELECT TOP 20 * FROM customer;

--Total Revenue Generated by Male vs Female customer
SELECT gender,SUM(purchase_amount) as revenue
from customer
group by gender

--Which customer is used a discount but still spent more than the average purchage amount
select customer_id , purchase_amount from customer
where discount_applied ='Yes' and purchase_amount >= (select Avg(purchase_amount) from customer)

-- Top 5 products with the highest average review rating
SELECT TOP 5
    item_purchased,
    ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS Average_Review_Rating
FROM customer
GROUP BY item_purchased
ORDER BY Average_Review_Rating DESC;

--Compare the average purchase amount between standard and express shipping
select shipping_type, ROUND(AVG(purchase_amount),2) as purchase_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type


--Do subscribed  customer spend more? Compare average spend and total revenue between subscribed and un-subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as average_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue,average_spend desc;

-- Top 5 products with highest percentage of purchases with discount
SELECT TOP 5
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*),2) AS Discount_Percentage
FROM customer
GROUP BY item_purchased
ORDER BY Discount_Percentage DESC;

--segment customer into new,returning and loyal based on their total number of  previous purchases,
--and show  the count of each segment

with customer_type as(
select customer_id,previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment, COUNT(*) as "Number of Customers"
from customer_type
group by customer_segment

--Top 3 most purchased products with in each category

with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

--Customers who are repeat  buyers more than 5 purchases also likely  to subscribe

select subscription_status, COUNT(customer_id) as repeate_buyers
from customer
where previous_purchases > 5
group by subscription_status

---What is the age revenue contribution of each  age group

select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

